Attack:
  name: DBA
  adversary_list: [0, 2, 4, 6]
  args:
    with_dp: true
    local_epochs: 2
    batch_size: 128
    loss_function: nll_loss
    optimizer:
      name: SGD
      args:
        lr: 0.05
        momentum: 0.9
    device: cuda
    poisoning_per_batch: 32
    poison_label_swap: 2
    stealth_rate: 0
    trigger:
      channels: 1
      trigger_num: 4
      # '=='
      0_poison_pattern: [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
      1_poison_pattern: [[0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14]]
      2_poison_pattern: [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]]
      3_poison_pattern: [[4, 9], [4, 10], [4, 11], [4, 12], [4, 13], [4, 14]]