Fed_rdp:
  sample_rate: 0.25
  eta: 0.5
  delta_g: 0.001
  noise_multiplier: 1.3
  max_grad_norm: 1.0
  max_physical_batch_size: 64
  budgets_setting:
    min_epsilon: 1.0
    max_epsilon: 5.0
    name: ThreeLevels
    args: [[0.2,0.3,0.5], [1.0, 2.0, 5.0]]
    BoundedPareto: [4, 0.1]
    BoundedMixGauss: [[0.7,0.2,0.1], [[0.1, 0.05], [1.0, 0.1], [5.0, 0.5]]]