Fed_rdp:
  sample_rate: 0.25
  eta: 0.5
  delta: 0.001
  delta_g: 0.1
  noise_config:
      type: constant

#      type: double_log
#      decay_rate: 0.5

#      type: log
#      decay_rate: 0.5

#      type: step
#      beta: 0.5
#      rounds: 50

  max_grad_norm: 1.0
  max_physical_batch_size: 64
  budgets_setting:
    min_epsilon: 5.0
    max_epsilon: 10.0
    name: ThreeLevels
    args: [[0.2,0.3,0.5], [5.0, 8.0, 10.0]]

#    name: BoundedPareto
#    args: [3, 5]

#    name: BoundedMixGauss
#    args: [[0.2,0.3,0.5], [[5, 0.5], [7, 0.5], [10, 0.5]]]
