Fed_rdp:
  sample_rate: 0.25
  eta: 0.5
  delta: 0.001
  delta_g: 0.1
  noise_config:
#      type: constant

#      type: step
#      beta: 0.8
#      rounds: 60

      type: inverse
      decay_rate: 0.5
  new_noise_config:
      type: inverse
      decay_rate: 0.05
  max_grad_norm: 3.0
  max_physical_batch_size: 128
  budgets_setting:
    min_epsilon: 1.0
    max_epsilon: 10.0
    name: ThreeLevels
    args: [[0.3,0.4,0.3], [5.0, 8.0, 10.0]]

#    name: BoundedPareto
#    args: [1, 1]

#    name: BoundedMixGauss
#    args: [[0.3, 0.4, 0.3], [[2.0, 1.0], [3.0, 1.0], [4.0, 1.0]]]
